name: Build & release wheels

on:
  push:
    branches:
      - main
  schedule:
    - cron:  '53 23 * * *'  # Daily at 23:53 UTC

jobs:
  build:
    name: Build & release wheels
    runs-on: ubuntu-latest
    steps:
      - name: Upgrade pip
        run: pip install --upgrade pip
      - name: Checkout
        uses: actions/checkout@v4
      - name: Install poetry
        run: pipx install poetry
      - name: Install CLI
        run: pipx install ./cli/
      - name: Build wheels from source
        run: build charms.json
      - name: Setup upterm session
        if: always()
        uses: lhotari/action-upterm@v1
      - name: Create GitHub release
        run: gh release create "build-$(date +%s)" ~/charmcraftcache-hub-ci/release/*
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    permissions:
      contents: write  # Needed to create release