name: Build & release wheels

on:
  push:
    branches:
      - main
  schedule:
    - cron:  '53 23 * * *'  # Daily at 23:53 UTC

jobs:
  build:
    name: Build & release wheels
    runs-on: ubuntu-latest
    steps:
      - name: Update pip
        run: pip install --upgrade pip
      - name: Checkout
        uses: actions/checkout@v4
      - name: Install poetry
        run: pipx install poetry
      - name: Install CLI
        run: pipx install ./cli/
      - run: build charms.json
      - name: Setup upterm session
        uses: lhotari/action-upterm@v1