name: Build & release wheels

on:
  push:
    branches:
      - main
  schedule:
    - cron:  '53 23 * * *'  # Daily at 23:53 UTC

jobs:
  build:
    name: Build & release wheels
    runs-on: ubuntu-latest
    steps:
      - name: Update python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'
      - name: Update pipx
        run: |
          python3 -m pip install pipx
          python3 -m pipx ensurepath
      - name: Checkout
        uses: actions/checkout@v4
      - name: Install CLI
        run: pipx install ./cli/
      - run: build charm_lock_files.json